---
- name: Install AppArmor
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
  become: yes
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - apparmor
    - apparmor-profiles
    - apparmor-utils
