---

- hosts: localhost
  tasks:
    - name: Install necessary software
      become: yes
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
        - auditd
        - libcap-ng-utils
    - name: Copy rules
      become: yes
      copy:
        remote_src: yes
        src: /usr/share/doc/auditd/examples/rules/{{ item }}
        dest: /etc/audit/rules.d/{{ item }}
      with_items:
        - 10-base-config.rules
        - 30-stig.rules.gz
        - 42-injection.rules
        - 43-module-load.rules
        - 99-finalize.rules
    - name: Unzip stig.rules
      become: yes
      command: /bin/gunzip -f /etc/audit/rules.d/30-stig.rules.gz
    - name: Disable noisy STIG rules
      become: yes
      replace:
        path: /etc/audit/rules.d/30-stig.rules
        regexp: "^(-.+-F key={{ item }})$"
        replace: '#\1'
      with_items:
        - perm_mod
        - delete
    - name: Create temp dir
      tempfile:
        state: directory
        suffix: temp
      register: tempdir_1
    - name: Copy Makefile
      copy:
        src: "{{ playbook_dir }}/../Makefile"
        dest: "{{ tempdir_1.path }}/"
        mode: 0600
    - name: Generate 31-privileged.rules
      become: yes
      make:
        chdir: "{{ tempdir_1.path }}"
        target: /etc/audit/rules.d/31-privileged.rules
    - name: Remove temp dir
      file:
        path: "{{ tempdir_1.path }}"
        state: absent
      when: tempdir_1.path is defined
    - name: Load the rules
      become: yes
      command: /usr/sbin/augenrules --load
