---
- name: Install ca-certificates package
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
  become: yes
  apt:
    name: ca-certificates
    update_cache: yes
- name: Copy ca-certificates.conf
  when: ansible_os_family != "RedHat"
  become: yes
  copy:
    src: "{{ playbook_dir }}/../newconfs/ca-certificates.conf.new"
    dest: /etc/ca-certificates.conf
- name: Install OpenSSL
  when: ansible_distribution == "Slackware"
  slackpkg:
    name: openssl
    state: present
- name: Run update-ca-certificates
  when: ansible_os_family != "RedHat"
  become: yes
  command: /usr/sbin/update-ca-certificates --verbose --fresh
