---
- name: Configure generic log retention period to {{ log_retention_time_in_months }} months
  become: yes
  replace:
    path: /etc/logrotate.conf
    regexp: '^(rotate\s+)[0-9]+$'
    replace: '\g<1>{{ log_retention_time_in_months * 4 }}'
    validate: '/bin/grep "^rotate\s\+{{ log_retention_time_in_months * 4 }}$" %s'
- name: Configure [bw]tmp retention period to {{ log_retention_time_in_months }} months
  become: yes
  replace:
    path: /etc/logrotate.conf
    regexp: '^(\s+rotate\s+)1$'
    replace: '\g<1>{{ log_retention_time_in_months }}'
    validate: '/bin/grep "^\s\+rotate\s\+{{ log_retention_time_in_months }}$" %s'
- name: Make log file default permissions group adm readable (Slackware)
  become: yes
  replace:
    path: /etc/logrotate.conf
    regexp: '^(create)$'
    replace: '\g<1> 0640 root adm'
    validate: '/bin/grep "^create 0640 root adm$" %s'
  when: ansible_distribution == "Slackware"
- name: Make btmp group adm readable (Slackware)
  become: yes
  replace:
    after: '/var/log/btmp {'
    path: /etc/logrotate.conf
    regexp: '^(\s+create\s+)0600 root root$'
    replace: '\g<1>0640 root adm'
    validate: '/bin/grep "^\s\+create\s\+0640 root adm$" %s'
  when: ansible_distribution == "Slackware"
- name: Make some log files append only (Slackware)
  become: yes
  when: ansible_distribution == "Slackware"
  copy:
    src: "{{ playbook_dir }}/../newconfs/logrotate.d/syslog.new"
    dest: /etc/logrotate.d/syslog
