---

- hosts: localhost
  vars:
    allowed_group: users
    defs_common:
      LOG_OK_LOGINS: "yes"
      UMASK: "077"
      SULOG_FILE: "/var/log/sulog"
      PASS_MAX_DAYS: "365"
      PASS_MIN_DAYS: "7"
      PASS_WARN_AGE: "30"
      FAILLOG_ENAB: "yes"
      SHA_CRYPT_MIN_ROUNDS: 500000
      ENCRYPT_METHOD: "SHA512"
      CHFN_RESTRICT: "rwh"
      DEFAULT_HOME: "no"
    defs_slackware:
      LASTLOG_ENAB: "yes"
      PASS_MIN_LEN: "8"
      FAIL_DELAY: "20"
      CREATE_HOME: "yes"
      SU_WHEEL_ONLY: "yes"
      PORTTIME_CHECKS_ENAB: "yes"
      NOLOGINS_FILE: "/etc/nologin"
      CHFN_AUTH: "yes"
  tasks:
    - name: Configure shadow password suite (common)
      become: yes
      replace:
        path: /etc/login.defs
        regexp: '^(# ?)?({{ item.key }}\s+)[^\s]+$'
        replace: '\g<2>{{ item.value }}'
        validate: '/bin/grep "^{{ item.key }}\s\+{{ item.value }}$" %s'
      with_dict: "{{ defs_common }}"
    - name: Configure shadow password suite (Slackware specific)
      become: yes
      when: ansible_distribution == "Slackware"
      replace:
        path: /etc/login.defs
        regexp: '^(# ?)?({{ item.key }}\s+)[^\s]+$'
        replace: '\g<2>{{ item.value }}'
        validate: '/bin/grep "^{{ item.key }}\s\+{{ item.value }}$" %s'
      with_dict: "{{ defs_slackware }}"
    - name: Configure login access control table (Slackware)
      when: ansible_distribution == "Slackware"
      become: yes
      blockinfile:
        path: /etc/login.access
        block: |
          # Allow local login for root and specific group
          +:root {{ allowed_group }}:LOCAL
          # Disallow all others
          -:ALL:ALL
