---
- name: Configure shadow password suite (common)
  become: yes
  replace:
    path: /etc/login.defs
    regexp: '^(# ?)?({{ item.key }}\s+)[^\s]+$'
    replace: '\g<2>{{ item.value }}'
    validate: '/bin/grep "^{{ item.key }}\s\+{{ item.value }}$" %s'
  with_dict: "{{ defs_common }}"
  vars:
    defs_common:
      LOG_OK_LOGINS: "yes"
      UMASK: "077"
      SULOG_FILE: "/var/log/sulog"
      PASS_MAX_DAYS: 365
      PASS_MIN_DAYS: 7
      PASS_WARN_AGE: 30
      FAILLOG_ENAB: "yes"
      SHA_CRYPT_MIN_ROUNDS: 500000
      ENCRYPT_METHOD: "SHA512"
      CHFN_RESTRICT: "rwh"
      DEFAULT_HOME: "no"
- name: Install glibc package (Slackware)
  when: ansible_distribution == "Slackware"
  become: yes
  command: slackpkg -batch=on -default_answer=y install glibc
# The login ACL following this task will actually start blocking access, so
# check that we are not locking ourselves out of the system being hardened.
- name: 'Check that some user(s) exist in "{{ allowed_group }}" group'
  shell: getent group {{ allowed_group }} | cut -d':' -f4
  register: members_of_group
  failed_when: members_of_group.stdout == ""
- name: Limit the list of terminals from which root can log in (securetty)
  become: yes
  copy:
    src: "{{ playbook_dir }}/../newconfs/securetty.new"
    dest: /etc/securetty
- name: Create /etc/profile.d/tmout.sh
  become: yes
  copy:
    src: "{{ playbook_dir }}/../newconfs/profile.d/tmout.sh.new"
    dest: /etc/profile.d/tmout.sh
    owner: root
    group: root
    mode: '0755'
- name: Warn users about expiring password
  become: yes
  copy:
    src: "{{ playbook_dir }}/../newconfs/expiry.sh.new"
    dest: /etc/profile.d/expiry.sh
    owner: root
    group: root
    mode: '0755'
- name: getent passwd
  getent:
    database: passwd
- name: Create /etc/ftpusers
  become: yes
  template:
    src: "{{ playbook_dir }}/templates/ftpusers.j2"
    dest: /etc/ftpusers
- include: login_defs-slackware.yml
  when: ansible_distribution == "Slackware"
- name: Verify integrity of group files
  become: yes
  command: grpck -r
