---

- hosts: localhost
  vars:
    container_name: test-container
  tasks:
    - name: Create a stopped container
      lxc_container:
        name: "{{ container_name }}"
        container_log: true
        template: debian
        state: stopped
        template_options: --release stretch
    - name: Start a container
      lxc_container:
        name: "{{ container_name }}"
        state: started
      register: containers_info
    - name: Wait for the network to be setup in the containers
      when: containers_info|changed
      pause: seconds=10
    - name: Get containers info now that IPs are available
      lxc_container:
        name: "{{ container_name }}"
      register: containers_info
    - name: Enable password auth for SSH
      lxc_container:
        name: "{{ container_name }}"
        container_command: "{{ item }}"
      with_items:
        - echo "root:debian" | chpasswd
        - sed -i 's/^#\?\(PermitRootLogin\) .*$/\1 yes/' /etc/ssh/sshd_config
        - systemctl restart ssh
        - apt-get -y install python
    - name: Register the hosts in the inventory
      add_host:
        name: "{{ containers_info.lxc_container.ips.0 }}"
        group: "{{ container_name }}"

- hosts: test-container
  vars:
    ansible_ssh_pass: debian
    ansible_become_method: su
  vars_files:
    - vars.yml
  tasks:
    - include: lynis.yml
    - name: Run Lynis
      command: /usr/sbin/lynis -Q
    - name: Get Lynis score
      command: 'sed -n "s/^.*Hardening index : \[\([0-9]\+\)\].*$/\1/p" /var/log/lynis.log'
      args:
        warn: false
      register: lynis_score_before
    - name: Lynis score before hardening
      debug:
        msg: "{{ lynis_score_before.stdout }}"
    - include: debian_packages.yml
    - include: login_defs.yml
    - include: services.yml
    - include: sysctl.yml
    - include: sysstat.yml
    - name: Run Lynis (again)
      command: /usr/sbin/lynis -Q
    - name: Get Lynis score
      command: 'sed -n "s/^.*Hardening index : \[\([0-9]\+\)\].*$/\1/p" /var/log/lynis.log'
      args:
        warn: false
      register: lynis_score_after
    - name: Lynis score
      debug:
        msg: "before={{ lynis_score_before.stdout }} after={{ lynis_score_after.stdout }}"
