---

- hosts: localhost
  vars:
    slackware_services:
      - /etc/rc.d/rc.inetd
      - /etc/rc.d/rc.yp
      - /etc/rc.d/rc.cups
      - /etc/rc.d/rc.cups-browsed
    debian_services:
      - avahi-daemon
      - bluetooth
      - cups
      - cups-browsed
      - atd
  tasks:
    - name: Stop & disable unwanted services (Debian)
      become: yes
      when: ansible_distribution == "Debian"
      service:
        name: avahi-daemon
        state: stopped
        enabled: no
      with_items: "{{ debian_services }}"
    - name: Stop unwanted services (Slackware)
      become: yes
      when: ansible_distribution == "Slackware"
      ignore_errors: yes
      command: /bin/sh "{{item}}" stop
      with_items: "{{ slackware_services }}"
    - name: Disable unwanted services (Slackware)
      become: yes
      when: ansible_distribution == "Slackware"
      file:
        path: "{{item}}"
        owner: root
        group: root
        mode: ugo-x
      with_items: "{{ slackware_services }}"
