---
- name: Stop & disable unwanted services (Debian)
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
  ignore_errors: yes
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items: "{{ debian_services }}"
- name: Stop unwanted services (Slackware)
  become: yes
  when: ansible_distribution == "Slackware"
  ignore_errors: yes
  command: /bin/sh /etc/rc.d/rc.{{ item }} stop
  with_items: "{{ slackware_services }}"
- name: Disable unwanted services (Slackware)
  become: yes
  when: ansible_distribution == "Slackware"
  ignore_errors: yes
  file:
    path: "/etc/rc.d/rc.{{ item }}"
    owner: root
    group: root
    mode: ugo-x
  with_items: "{{ slackware_services }}"
- name: Restrict cron (cron.allow)
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
  become: yes
  file:
    path: /etc/cron.allow
    state: touch
    owner: root
    group: crontab
    mode: '0640'
- name: Restrict cron (cron.deny)
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
  become: yes
  file:
    path: /etc/cron.deny
    state: absent
- name: Restrict cron (Slackware)
  when: ansible_distribution == "Slackware"
  become: yes
  file:
    path: /usr/bin/crontab
    group: wheel
    mode: '4710'
- name: Harden SSH daemon configuration
  become: yes
  template:
    src: "{{ playbook_dir }}/templates/sshd_config-{{ ansible_distribution }}.j2"
    dest: /etc/ssh/sshd_config
    validate: /usr/sbin/sshd -t -f %s
- name: Restart sshd
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
  become: yes
  service:
    name: ssh
    state: restarted
- name: Restart sshd (Slackware)
  when: ansible_distribution == "Slackware"
  become: yes
  command: /bin/sh /etc/rc.d/rc.sshd restart
