---
- name: 'Check that some user(s) exist in "sudo" group'
  shell: getent group sudo | cut -d':' -f4
  register: members_of_group
  failed_when: members_of_group.stdout == ""
  when: ansible_distribution == "Debian"
- name: 'Check that some user(s) exist in "wheel" group'
  shell: getent group wheel | cut -d':' -f4
  register: members_of_group
  failed_when: members_of_group.stdout == "" or members_of_group.stdout == "root"
  when: ansible_distribution == "Slackware"
- name: 'Configure /etc/sudoers'
  block:
  - name: 'Create /etc/sudoers.new'
    template:
      src: "{{ playbook_dir }}/templates/sudoers.j2"
      dest: /etc/sudoers.new
      mode: '0440'
      owner: root
      group: root
  - name: 'Validate /etc/sudoers.new'
    command: visudo -cs -f /etc/sudoers.new
  - name: 'Copy /etc/sudoers.new to /etc/sudoers'
    copy:
      remote_src: yes
      src: /etc/sudoers.new
      dest: /etc/sudoers
  - name: 'Remove /etc/sudoers.new'
    file:
      path: /etc/sudoers.new
      state: absent
  when: ansible_distribution == "Slackware" or ansible_distribution == "Debian"
  become: yes
# https://www.raspberrypi.org/documentation/configuration/security.md
- name: 'Remove /etc/sudoers.d/010_pi-nopasswd'
  become: yes
  file:
    path: /etc/sudoers.d/010_pi-nopasswd
    state: absent
  when: ansible_distribution == "Debian" and ansible_lsb.id == "Raspbian"
- include: filesystem-sudoers.yml
