---
allowed_group: users
log_retention_time_in_months: 6
slackware_services:
  - inetd
  - yp
  - cups
  - cups-browsed
debian_services:
  - avahi-daemon
  - bluetooth
  - cups
  - cups-browsed
  - atd
allowed_services:
  - sshd
